// Generated by gencpp from file fr5_moveit_config/GoToPose.msg
// DO NOT EDIT!


#ifndef FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSE_H
#define FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSE_H

#include <ros/service_traits.h>


#include <fr5_moveit_config/GoToPoseRequest.h>
#include <fr5_moveit_config/GoToPoseResponse.h>


namespace fr5_moveit_config
{

struct GoToPose
{

typedef GoToPoseRequest Request;
typedef GoToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPose
} // namespace fr5_moveit_config


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fr5_moveit_config::GoToPose > {
  static const char* value()
  {
    return "14fb54e9e518f55d418823395ca25d0b";
  }

  static const char* value(const ::fr5_moveit_config::GoToPose&) { return value(); }
};

template<>
struct DataType< ::fr5_moveit_config::GoToPose > {
  static const char* value()
  {
    return "fr5_moveit_config/GoToPose";
  }

  static const char* value(const ::fr5_moveit_config::GoToPose&) { return value(); }
};


// service_traits::MD5Sum< ::fr5_moveit_config::GoToPoseRequest> should match
// service_traits::MD5Sum< ::fr5_moveit_config::GoToPose >
template<>
struct MD5Sum< ::fr5_moveit_config::GoToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fr5_moveit_config::GoToPose >::value();
  }
  static const char* value(const ::fr5_moveit_config::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fr5_moveit_config::GoToPoseRequest> should match
// service_traits::DataType< ::fr5_moveit_config::GoToPose >
template<>
struct DataType< ::fr5_moveit_config::GoToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::fr5_moveit_config::GoToPose >::value();
  }
  static const char* value(const ::fr5_moveit_config::GoToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fr5_moveit_config::GoToPoseResponse> should match
// service_traits::MD5Sum< ::fr5_moveit_config::GoToPose >
template<>
struct MD5Sum< ::fr5_moveit_config::GoToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fr5_moveit_config::GoToPose >::value();
  }
  static const char* value(const ::fr5_moveit_config::GoToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fr5_moveit_config::GoToPoseResponse> should match
// service_traits::DataType< ::fr5_moveit_config::GoToPose >
template<>
struct DataType< ::fr5_moveit_config::GoToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::fr5_moveit_config::GoToPose >::value();
  }
  static const char* value(const ::fr5_moveit_config::GoToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSE_H
