// Generated by gencpp from file fr5_moveit_config/GoToPoseResponse.msg
// DO NOT EDIT!


#ifndef FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSERESPONSE_H
#define FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fr5_moveit_config
{
template <class ContainerAllocator>
struct GoToPoseResponse_
{
  typedef GoToPoseResponse_<ContainerAllocator> Type;

  GoToPoseResponse_()
    : success(false)  {
    }
  GoToPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseResponse_

typedef ::fr5_moveit_config::GoToPoseResponse_<std::allocator<void> > GoToPoseResponse;

typedef boost::shared_ptr< ::fr5_moveit_config::GoToPoseResponse > GoToPoseResponsePtr;
typedef boost::shared_ptr< ::fr5_moveit_config::GoToPoseResponse const> GoToPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator1> & lhs, const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator1> & lhs, const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fr5_moveit_config

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fr5_moveit_config/GoToPoseResponse";
  }

  static const char* value(const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fr5_moveit_config::GoToPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FR5_MOVEIT_CONFIG_MESSAGE_GOTOPOSERESPONSE_H
